spring:
  application:
    name: pokemon-api

  datasource:
    url: jdbc:h2:mem:pokemondb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: org.hibernate.dialect.H2Dialect

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console